{
    "name": "Aabaan Service Scheduler",
    "summary": "Easy scheduling for pest control and water tank service visits",
    "version": "19.0.1.5.1",
    "category": "Services",
    "author": "Core2Plus",
    "license": "LGPL-3",
    "depends": [
        "base",
        "hr",
        "account",
        "sale_management",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "views/aabaan_service_contract_views.xml",
        "views/aabaan_service_visit_views.xml",
        "views/wizard_views.xml",
        "views/menu_views.xml",
        "views/ceo_financial_views.xml",
        "views/ceo_dashboard_views.xml",
    ],
    "application": True,
    "installable": True,
}
