{
    "name": "Aabaan Service Scheduler",
    "summary": "Easy scheduling for pest control and water tank service visits",
    "version": "19.0.1.8.3",
    "category": "Services",
    "author": "Core2Plus",
    "license": "LGPL-3",
    "depends": [
        "base",
        "hr",
        "account",
        "sale_management",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "views/aabaan_service_contract_views.xml",
        "views/aabaan_service_visit_views.xml",
        "views/wizard_views.xml",
        "views/supervisor_dashboard_views.xml",
        "views/supervisor_command_centre_views.xml",
        "views/menu_views.xml",
        "views/ceo_financial_views.xml",
        "views/ceo_dashboard_views.xml",
        "views/ceo_command_centre_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "aabaan_service_scheduler/static/src/ceo_command_centre/ceo_command_centre.scss",
            "aabaan_service_scheduler/static/src/ceo_command_centre/ceo_command_centre.js",
            "aabaan_service_scheduler/static/src/ceo_command_centre/ceo_command_centre.xml",
            "aabaan_service_scheduler/static/src/supervisor_command_centre/supervisor_command_centre.scss",
            "aabaan_service_scheduler/static/src/supervisor_command_centre/supervisor_command_centre.js",
            "aabaan_service_scheduler/static/src/supervisor_command_centre/supervisor_command_centre.xml",
        ],
    },
    "application": True,
    "installable": True,
}
